name: Hertz Freerider Bevakning

on:
  # Manuell körning och schemalagd var 30:e minut
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check_freerider:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run monitoring script
        env:
          NTFY_TOPIC: Hertzbil_Sthlm-OSD
        run: python hertz_bevakning.py